blank_issues_enabled: false
contact_links:
  - name: Theory question
    url: https://github.com/JamesPagetButler/confluent-trust/discussions
    about: For theory questions, prefer Discussions over Issues.
